# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: key_value_store.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'key_value_store.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15key_value_store.proto\"*\n\x0cStoreRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"G\n\rStoreResponse\x12\x11\n\x02ok\x18\x01 \x01(\x0b\x32\x03.OkH\x00\x12\x17\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.ErrorH\x00\x42\n\n\x08response\"\x1e\n\x0fRetrieveRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"P\n\x10RetrieveResponse\x12\x17\n\x05value\x18\x01 \x01(\x0b\x32\x06.ValueH\x00\x12\x17\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x06.ErrorH\x00\x42\n\n\x08response\"\x11\n\x02Ok\x12\x0b\n\x03key\x18\x01 \x01(\t\"#\n\x05Value\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x18\n\x05\x45rror\x12\x0f\n\x07message\x18\x01 \x01(\t2h\n\rKeyValueStore\x12&\n\x05Store\x12\r.StoreRequest\x1a\x0e.StoreResponse\x12/\n\x08Retrieve\x12\x10.RetrieveRequest\x1a\x11.RetrieveResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'key_value_store_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STOREREQUEST']._serialized_start=25
  _globals['_STOREREQUEST']._serialized_end=67
  _globals['_STORERESPONSE']._serialized_start=69
  _globals['_STORERESPONSE']._serialized_end=140
  _globals['_RETRIEVEREQUEST']._serialized_start=142
  _globals['_RETRIEVEREQUEST']._serialized_end=172
  _globals['_RETRIEVERESPONSE']._serialized_start=174
  _globals['_RETRIEVERESPONSE']._serialized_end=254
  _globals['_OK']._serialized_start=256
  _globals['_OK']._serialized_end=273
  _globals['_VALUE']._serialized_start=275
  _globals['_VALUE']._serialized_end=310
  _globals['_ERROR']._serialized_start=312
  _globals['_ERROR']._serialized_end=336
  _globals['_KEYVALUESTORE']._serialized_start=338
  _globals['_KEYVALUESTORE']._serialized_end=442
# @@protoc_insertion_point(module_scope)
